Mobile Joomla! License Agreement

"Mobile Joomla! Product" means any Mobile Joomla! Software product (including but not limited to extensions, components, modules, plugins, templates, language files, documents and each combination formed) or software code included, attached, related, downloaded or viewed, in each case, created, supplied or owned by Kuneri Ltd.

"PHP Elements" means, any PHP file, code or element.

"Non-PHP Elements" means, any file, code, element that is not PHP file, code or element, such as (including but not limited to) image, CSS or JavaScript. 

1. Every and each Mobile Joomla! Product is released under GNU/GPL v2 license (see below) for the PHP Elements.
2. Every and each Mobile Joomla! Product is released under Mobile Joomla! Proprietary License (see below) for the Non-PHP Elements. The Non-PHP Elements are not compiled together with PHP, but instead sent independent of PHP code and combined in a client's browser, which is why they are not GNU/GPLv2 compliant as stated by the GNU/GPLv2 license.
3. Every and each Mobile Joomla! Product is licensed per one domain. You agree to provide a correct URL (where it's required).
4. We reserve the right to make changes to this agreement without any notice, however we commit to inform you for major changes. 


Mobile Joomla! website: http://www.mobilejoomla.com
Mobile Joomla! twitter: http://www.twitter.com/mobilejoomla
Mobile Joomla! blog: http://www.mobilejoomla.com/blog.html
GNU/GPL v2 license: http://www.gnu.org/licenses/gpl-2.0.html#SEC1
Mobile Joomla! Proprietary License: http://www.mobilejoomla.com/proprietary-license.html
